// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PingT struct {
	TimeStamp int64
}

func (t *PingT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	PingStart(builder)
	PingAddTimeStamp(builder, t.TimeStamp)
	return PingEnd(builder)
}

func (rcv *Ping) UnPackTo(t *PingT) {
	t.TimeStamp = rcv.TimeStamp()
}

func (rcv *Ping) UnPack() *PingT {
	if rcv == nil { return nil }
	t := &PingT{}
	rcv.UnPackTo(t)
	return t
}

type Ping struct {
	_tab flatbuffers.Table
}

func GetRootAsPing(buf []byte, offset flatbuffers.UOffsetT) *Ping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ping{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPing(buf []byte, offset flatbuffers.UOffsetT) *Ping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Ping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Ping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ping) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Ping) TimeStamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ping) MutateTimeStamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func PingStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PingAddTimeStamp(builder *flatbuffers.Builder, timeStamp int64) {
	builder.PrependInt64Slot(0, timeStamp, 0)
}
func PingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
