// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package gotham

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnyMsg struct {
	Any                  *any.Any `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyMsg) Reset()         { *m = AnyMsg{} }
func (m *AnyMsg) String() string { return proto.CompactTextString(m) }
func (*AnyMsg) ProtoMessage()    {}
func (*AnyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *AnyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyMsg.Unmarshal(m, b)
}
func (m *AnyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyMsg.Marshal(b, m, deterministic)
}
func (m *AnyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyMsg.Merge(m, src)
}
func (m *AnyMsg) XXX_Size() int {
	return xxx_messageInfo_AnyMsg.Size(m)
}
func (m *AnyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AnyMsg proto.InternalMessageInfo

func (m *AnyMsg) GetAny() *any.Any {
	if m != nil {
		return m.Any
	}
	return nil
}

type PingMsg struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMsg) Reset()         { *m = PingMsg{} }
func (m *PingMsg) String() string { return proto.CompactTextString(m) }
func (*PingMsg) ProtoMessage()    {}
func (*PingMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *PingMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMsg.Unmarshal(m, b)
}
func (m *PingMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMsg.Marshal(b, m, deterministic)
}
func (m *PingMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMsg.Merge(m, src)
}
func (m *PingMsg) XXX_Size() int {
	return xxx_messageInfo_PingMsg.Size(m)
}
func (m *PingMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PingMsg proto.InternalMessageInfo

func (m *PingMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AnyMsg)(nil), "gotham.AnyMsg")
	proto.RegisterType((*PingMsg)(nil), "gotham.PingMsg")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcf, 0x2f, 0xc9, 0x48,
	0xcc, 0x95, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x26, 0x95, 0xa6, 0xe9,
	0x27, 0xe6, 0x55, 0x42, 0x94, 0x28, 0x19, 0x70, 0xb1, 0x39, 0xe6, 0x55, 0xfa, 0x16, 0xa7, 0x0b,
	0xa9, 0x71, 0x31, 0x27, 0xe6, 0x55, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8, 0x41,
	0xb4, 0xe8, 0xc1, 0xb4, 0xe8, 0x39, 0xe6, 0x55, 0x06, 0x81, 0x14, 0x28, 0x29, 0x73, 0xb1, 0x07,
	0x64, 0xe6, 0xa5, 0x83, 0xb4, 0x48, 0x70, 0xb1, 0x43, 0x2d, 0x04, 0x6b, 0xe3, 0x0c, 0x82, 0x71,
	0x93, 0xd8, 0xc0, 0xfa, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x79, 0x82, 0x49, 0x91,
	0x00, 0x00, 0x00,
}
